using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("NinaOtel")]
[assembly: AssemblyDescription("Exports NINA telemetry to an OTLP collector.")]
[assembly: AssemblyCompany("japz")]
[assembly: AssemblyProduct("NinaOtel")]
[assembly: AssemblyCopyright("Copyright (c) 2026")]
[assembly: AssemblyVersion("0.1.0.3")]
[assembly: AssemblyFileVersion("0.1.0.3")]
[assembly: AssemblyInformationalVersion("0.1.0-alpha.4")]
[assembly: Guid("7311D7B5-0BBD-45AB-8E29-DB09B289A798")]
[assembly: AssemblyMetadata("Homepage", "https://github.com/japz/nina-otel")]
[assembly: AssemblyMetadata("Repository", "https://github.com/japz/nina-otel")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://github.com/japz/nina-otel/blob/main/LICENSE")]
[assembly: AssemblyMetadata("ChangelogURL", "https://github.com/japz/nina-otel/releases")]
[assembly: AssemblyMetadata("Tags", "telemetry,opentelemetry,otlp,observability")]
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]
[assembly: AssemblyMetadata("LongDescription", "NinaOtel exports NINA telemetry to an OpenTelemetry OTLP collector. It provides the plugin shell, options UI, telemetry pipeline, bounded buffering, and add-on host foundation for NINA, PHD2, scheduler, night summary, and device-specific telemetry.")]
